#!/bin/bash

declare -r SANDBOX_HOME=${SANDBOX_HOME:-$HOME/.cabal-sandbox}
declare -r COMMAND="`basename $0`"

usage() {
    echo "Usage: $0 register"
    return 1
}

detect_sandbox() {
    local sub="${1:+/$1}"
    local cwd="${2:-$PWD}"
    local tmp sandbox
    while true; do
        sandbox="$cwd/.cabal-sandbox$sub"
        if [[ -d "$sandbox" ]]; then
            echo "$sandbox"
            return
        fi
        tmp=`dirname $cwd`
        if [[ $tmp = $cwd ]]; then
            break
        fi
        cwd=$tmp
    done
}

register() {
    local -r launcher="$COMMAND"
    local -r sandbox="`detect_sandbox bin`"
    if [[ ! "$sandbox" ]]; then
        echo "Could not find .cabal-sandbox directory or executables." >&2
        return 1
    fi
    mkdir -p "$SANDBOX_HOME/bin"
    for name in "$sandbox"/*; do
        ln -s "$launcher" "$SANDBOX_HOME/bin/`basename $name`"
    done
    return 0
}

execute() {
    local -r sandbox="`detect_sandbox bin`"
    local -r binpath="$sandbox/$COMMAND"
    if [[ ! "$sandbox" ]] || [[ ! -x "$binpath" ]]; then
        echo "cabal-sandbox: command not found: $COMMAND" >&2
        return 1
    fi
    exec "$binpath" "$@"
}

if [[ $COMMAND = 'cabal-sandbox' ]]; then
    case "$1" in
        register)
            register
            ;;
        *)
            usage
            ;;
    esac
    exit $?
else
    execute "$@"
fi
